### ISSUE TITLE
AttributeError on command pallet invokation

### ISSUE THREAD

**Issue by spamwax** [myurtoglu/NamespaceTool#1]
I get this error whenever I invoke my command pallet through shortcut:

`File "C++NamespaceTool in ~/Library/Application Support/Sublime Text 3/Installed Packages/C++NamespaceTool.sublime-package", line 160, in is_visible
AttributeError: 'NoneType' object has no attribute 'lower'`

This happens even if a non-C++ file is the active tab!

I am guessing a check like this would help (before [line 160](https://github.com/myurtoglu/NamespaceTool/blob/master/C%2B%2BNamespaceTool.py#L160)):

``` Python
if not self.view or self.view.is_scratch() or self.view.file_name() is None:
        return False
```

**Comment by myurtoglu** [comment]
I added your fix and it should show up on PackageControl soon as version 1.0.1. Thank you very much for your help.
